//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Jox.Parsing.AST
{
    public interface IStmt
    {
        public interface IVisitor<T>
        {
            T VisitExpressionStmt(Expression stmt);
            T VisitIfStmt(If stmt);
            T VisitPrintStmt(Print stmt);
            T VisitWhileStmt(While stmt);
            T VisitVarStmt(Var stmt);
            T VisitBlockStmt(Block stmt);
        }

        T Accept<T>(IVisitor<T> visitor);

        public struct Expression : IStmt
        {
            public IExpr expression;

            public Expression(IExpr expression)
            {
                this.expression = expression;
            }

            public T Accept<T>(IVisitor<T> visitor)
            {
                return visitor.VisitExpressionStmt(this);
            }
        }

        public struct If : IStmt
        {
            public IExpr condition;
            public IStmt thenBranch;
            public IStmt elseBranch;

            public If(IExpr condition, IStmt thenBranch, IStmt elseBranch)
            {
                this.condition = condition;
                this.thenBranch = thenBranch;
                this.elseBranch = elseBranch;
            }

            public T Accept<T>(IVisitor<T> visitor)
            {
                return visitor.VisitIfStmt(this);
            }
        }

        public struct Print : IStmt
        {
            public IExpr expression;

            public Print(IExpr expression)
            {
                this.expression = expression;
            }

            public T Accept<T>(IVisitor<T> visitor)
            {
                return visitor.VisitPrintStmt(this);
            }
        }

        public struct While : IStmt
        {
            public IExpr condition;
            public IStmt body;

            public While(IExpr condition, IStmt body)
            {
                this.condition = condition;
                this.body = body;
            }

            public T Accept<T>(IVisitor<T> visitor)
            {
                return visitor.VisitWhileStmt(this);
            }
        }

        public struct Var : IStmt
        {
            public Token ident;
            public IExpr initializer;

            public Var(Token ident, IExpr initializer)
            {
                this.ident = ident;
                this.initializer = initializer;
            }

            public T Accept<T>(IVisitor<T> visitor)
            {
                return visitor.VisitVarStmt(this);
            }
        }

        public struct Block : IStmt
        {
            public List<IStmt> statements;

            public Block(List<IStmt> statements)
            {
                this.statements = statements;
            }

            public T Accept<T>(IVisitor<T> visitor)
            {
                return visitor.VisitBlockStmt(this);
            }
        }

    }
}
